// Handling Uncaught Exception
exports.uncaughtExceptionHanndler = () => process.on("uncaughtException", (err) => {
    console.log(`Error: ${err.message}`);
    console.log(`Shutting down the server due to Uncaught Exception`);
    process.exit(1);
  });